<a href="https://colab.research.google.com/github/urmilapol/urmilapolprojects/blob/master/numpylecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction & Welcome
"Hello everyone, and welcome to today's masterclass on NumPy—which stands for Numerical Python.

If you have your sights set on Data Science, Data Analytics, or Machine Learning, NumPy is your absolute starting point. It is the bedrock upon which major libraries like Pandas and Matplotlib are built. If you don't master NumPy, you'll struggle with the advanced tools down the road.

Now, you might ask, 'Why can't we just use native Python lists?' Well, Python lists are highly versatile, but they are dramatically slow for heavy math. NumPy introduces the ndarray (N-dimensional array). It stores data efficiently in a continuous block of memory and relies on compiled C-code under the hood. This means operations that take seconds on a Python list happen in milliseconds with NumPy."

Step 2: Verification and Importing
"Let's jump into the code. If you are using Google Colab, NumPy is already installed for you. All we need to do is import it into our workspace.

We write:

Python
import numpy as np
By convention, we alias it as np to save keystrokes. Let's print out np.__version__ just to ensure everything loaded properly. If you see a version number outputted on your screen, you are ready to roll."

Step 3: Creating Arrays
"Now let's talk about creating our very first array. An array is simply a container that holds multiple values, but unlike a list, every value must be of the exact same data type—usually integers or floats.

Look at the code. We start with a normal Python list: [1, 2, 3]. We pass it to np.array(list1) and print it. Notice something interesting? The output [1 2 3] doesn't have commas! That's the visual signature of a NumPy array. If we check its type, it tells us it's an ndarray—an N-Dimensional array. Because it's just a single row of numbers, its .ndim or number of dimensions is 1.

What if we stack two lists together? We pass a list of lists: [[1, 2, 3], [4, 5, 6]]. NumPy instantly converts this into a 2D array, creating a structured matrix of rows and columns. Its .ndim jumps to 2.

If we go a step further and nest matrices inside matrices, we create a 3D array, which you can visualize as a cube or a stack of grids. Its dimension is 3."

Step 4: Array Attributes
"Once you have an array, you need to be able to inspect its structural blueprint. We use three critical attributes for this:

.shape: This is a tuple that tells you the layout. For our 2D array, it returns (2, 3), which translates to exactly 2 rows and 3 columns.

.size: This returns the total count of individual elements across the entire array. For a 2x3 matrix, it multiplies the dimensions and returns 6.

.dtype: This tells us what kind of data lives inside. Here, it says int64, meaning they are 64-bit integers."

Step 5: Array Initialization Methods
"Manually typing out lists to make arrays gets tedious. NumPy provides several brilliant shortcut functions to initialize arrays with dummy data instantly:

Need a blank slate of zeros? Use np.zeros((2, 3)). It builds a 2 row, 3 column grid of pure 0.0 floats.

Need an array of ones? Use np.ones((1, 3)).

Want a specific number instead? Use np.full((3, 2), 9). This creates a 3x2 matrix entirely packed with the number 9.

Working with linear algebra? np.eye(3) generates a 3x3 Identity Matrix, where a clean diagonal line of 1s cuts through a sea of 0s.

Want a sequence of numbers? np.arange(1, 10, 2) functions just like Python's native range loop, generating numbers from 1 up to (but excluding) 10 with a step size of 2.

Need a specific split? np.linspace(1, 10, 4) tells NumPy: 'Start at 1, end at 10, and chop it up into exactly 4 evenly-spaced intervals.'

Finally, if you need synthetic data for testing, np.random.randint(1, 100, (3, 3)) creates a 3x3 grid packed completely with random whole numbers between 1 and 100."

Step 6: Indexing and Slicing
"Let's move on to pulling data out of our arrays. If you understand basic Python strings or lists, this will feel very familiar, but with a powerful multi-dimensional twist.

For a 1D array [1, 3, 5, 7, 9]:

a[0] gives us the very first element: 1.

a[-1] uses negative indexing to grab the last element from the right: 9.

Slicing follows the [start : stop : step] syntax. a[0:3] grabs index 0, 1, and 2. Remember, the stop index is always exclusive, so index 3 is left out.

Now, let's look at a 2D array. To pull data out, the syntax evolves to: array[row_selector, column_selector].
If we write arr2[0, 0], we are targeting row 0, column 0.
But look at this powerful slice: arr2[:, 0]. The colon : in the row spot tells NumPy: 'Give me ALL rows.' The 0 in the column spot says: 'But only from the first column.' This extracts an entire vertical column slice instantly!"

Step 7: Reshaping and Flattening
"Sometimes data arrives in the wrong shape. For example, you might get a flat 1D array of 6 items, but your machine learning model expects a 2D matrix.

We can fix this instantly using .reshape((2, 3)). It effortlessly bends those 6 elements into a structured 2-row, 3-column matrix. The only rule is the math must match. You cannot reshape 6 elements into a 2x4 matrix because 8 slots are required, and NumPy will throw an error.

The exact opposite operation is Flattening. If you have a complex 2D or 3D matrix and want to crush it back down into a single, simple line of numbers, you call .flatten()."

Step 8: Stacking and Splitting
"Think of stacking like building a brick wall. If you have two separate 1D arrays, you can combine them using two different strategies:

np.vstack() (Vertical Stack): This places the arrays on top of each other, row-by-row, combining two 1D arrays into a single 2D matrix.

np.hstack() (Horizontal Stack): This glues them together side-by-side, creating one long continuous 1D array.

Conversely, you can tear matrices apart using np.hsplit() or np.vsplit(). In our code notebook, we take our vertically stacked matrix and split it horizontally into 3 separate pieces, cutting cleanly through the columns."

Step 9: Mathematical & Statistical Operations
"This is where NumPy shines. In pure Python, if you wanted to add 10 to every number in a list, you'd have to write a slow for loop.

In NumPy, you just type math_arr + 10. NumPy applies this operation element-wise to every single item instantly. You can do the same to find the square root of every element using np.sqrt(math_arr).

If you have two arrays of the same shape, you can multiply them element-by-element using np.multiply(a, b). If you want the true algebraic Dot Product (multiplying corresponding elements and adding the total sums together), you use np.dot(a, b).

Matrix manipulation is just as easy. Flipping a matrix diagonally—turning rows into columns—is called a Transpose, and you achieve it simply by appending a capital .T to your array variable name.

For data analysis, you have rapid built-in statistics: np.sum(), np.mean(), and np.max() allow you to instantly aggregate metrics across millions of data points."

Step 10: Comparison & Broadcasting
"When you compare two arrays using ==, NumPy checks them element-by-element, returning an array of Booleans showing exactly where they match. If you want a single True or False answer for whether the two arrays are identical down to the last digit, you use np.array_equal(a, b).

Now let's talk about a core NumPy superpower: Broadcasting.
What happens if you try to add a 2D matrix to a single 1D row vector? Their shapes don't match! In standard math, this is illegal. But NumPy looks at the dimensions and says: 'I can stretch this smaller vector downwards, duplicating it across rows without wasting computer memory, so the math works.' The result is a seamless calculation that keeps your code incredibly fast."

Step 11: Handling Null Values
"When working with messy real-world data, you will frequently encounter missing or corrupted data points.

NumPy represents missing data as np.nan (Not a Number) and mathematically infinite calculations as np.inf. Because NaN values act like structural landmines—they ruin any math operation they touch—you have to locate them.

We use np.isnan(clean_data), which returns a Boolean mask spotlighting exactly where the missing values live. To patch the holes, we call np.nan_to_num(clean_data). This automatically swaps out problematic NaN values with a safe 0.0 default so your data science pipeline doesn't crash."

Step 12: Saving and Loading Arrays
"Finally, once you've cleaned your data and calculated your metrics, you need to store it so you don't lose your progress.

To save an array locally to your disk, use:

Python
np.save('my_colab_array.npy', save_arr)
This writes the data out as a compact, ultra-fast binary file with a .npy extension. When you return tomorrow or need to load it into a different notebook, you simply execute np.load('my_colab_array.npy'), and your array is restored instantly, exactly as you left it.

Conclusion & Assignment
That brings us to the end of our foundational NumPy lecture! You now possess the core vocabulary of numerical computing in Python.

To solidify this knowledge, please take a look at the homework assignment section at the bottom of your notebook. Practice creating an array, reshaping it, masking out any null values, and saving the final file. Run the code, play with the parameters, and I'll see you all in the next lecture where we dive into Pandas!"

In [1]:
# ==============================================================================
# COMPLETE NUMPY DATA SCIENCE TUTORIAL
# ==============================================================================
# This notebook covers everything from basic array creation to advanced operations.
# Execute this cell to see all the outputs step-by-step.

# ------------------------------------------------------------------------------
# STEP 2: Installation & Import
# ------------------------------------------------------------------------------
# In Google Colab, NumPy is pre-installed. We just need to import it.
import numpy as np

print("--- STEP 2: VERSION CHECK ---")
print(f"NumPy Version: {np.__version__}\n")

# ------------------------------------------------------------------------------
# STEP 3: Creating Arrays
# ------------------------------------------------------------------------------
print("--- STEP 3: CREATING ARRAYS ---")

# 1D Array
list1 = [1, 2, 3]
arr1 = np.array(list1)
print("1D Array:\n", arr1)
print("Type:", type(arr1))
print("Dimensions (ndim):", arr1.ndim, "\n")

# 2D Array
list2 = [4, 5, 6]
arr2 = np.array([list1, list2])
print("2D Array:\n", arr2)
print("Dimensions (ndim):", arr2.ndim, "\n")

# 3D Array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr3)
print("Dimensions (ndim):", arr3.ndim, "\n")

# ------------------------------------------------------------------------------
# STEP 4: Array Attributes
# ------------------------------------------------------------------------------
print("--- STEP 4: ARRAY ATTRIBUTES ---")
print("Shape of arr2:", arr2.shape)  # (rows, columns)
print("Size of arr2 (Total elements):", arr2.size)
print("Data Type of arr2:", arr2.dtype, "\n")

# ------------------------------------------------------------------------------
# STEP 5: Array Initialization Methods
# ------------------------------------------------------------------------------
print("--- STEP 5: INITIALIZATION METHODS ---")
print("Zeros Array (2x3):\n", np.zeros((2, 3)))
print("Ones Array (1x3):\n", np.ones((1, 3)))
print("Full Array (3x2 with 9s):\n", np.full((3, 2), 9))
print("Identity Matrix (3x3):\n", np.eye(3))
print("arange (1 to 10 with step 2):\n", np.arange(1, 10, 2))
print("linspace (4 elements between 1 and 10):\n", np.linspace(1, 10, 4))
print("Random Integers (3x3 from 1 to 100):\n", np.random.randint(1, 100, (3, 3)), "\n")

# ------------------------------------------------------------------------------
# STEP 6: Indexing and Slicing
# ------------------------------------------------------------------------------
print("--- STEP 6: INDEXING & SLICING ---")
a = np.array([1, 3, 5, 7, 9])
print("Base 1D Array:", a)
print("Positive Index 0:", a[0])
print("Negative Index -1:", a[-1])
print("Slicing (First 3 elements):", a[0:3])
print("Slicing with step 2:", a[0::2], "\n")

# 2D Indexing and Slicing
print("Base 2D Array (arr2):\n", arr2)
print("Element at row 0, col 0:", arr2[0, 0])
print("Extract entire first column:", arr2[:, 0], "\n")

# ------------------------------------------------------------------------------
# STEP 7: Reshaping and Flattening
# ------------------------------------------------------------------------------
print("--- STEP 7: RESHAPING & FLATTENING ---")
flat_arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = flat_arr.reshape((2, 3))
print("Original 1D:", flat_arr)
print("Reshaped to 2x3:\n", reshaped)
print("Flattened back to 1D:", reshaped.flatten(), "\n")

# ------------------------------------------------------------------------------
# STEP 8: Stacking and Splitting
# ------------------------------------------------------------------------------
print("--- STEP 8: STACKING & SPLITTING ---")
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
vs = np.vstack((x, y))
hs = np.hstack((x, y))
print("Vertical Stack:\n", vs)
print("Horizontal Stack:", hs)

# Splitting matrix vs back into two pieces horizontally
split_pieces = np.hsplit(vs, 3)
print("Horizontal Split into 3 pieces:")
for i, piece in enumerate(split_pieces):
    print(f"Piece {i}:\n", piece)
print()

# ------------------------------------------------------------------------------
# STEP 9: Mathematical & Statistical Operations
# ------------------------------------------------------------------------------
print("--- STEP 9: MATHEMATICAL & STATISTICAL OPERATIONS ---")
math_arr = np.array([1, 4, 9])
print("Base Array:", math_arr)
print("Scalar Addition (+10):", math_arr + 10)
print("Square Root:", np.sqrt(math_arr))

# Operations between multiple arrays
a_ops = np.array([1, 2, 3])
b_ops = np.array([4, 5, 6])
print("Element-wise Multiplication:", np.multiply(a_ops, b_ops))
print("Dot Product:", np.dot(a_ops, b_ops))

# Transpose
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Matrix:\n", matrix)
print("Transposed Matrix:\n", matrix.T)

# Statistics
print("Sum:", np.sum(matrix))
print("Mean:", np.mean(matrix))
print("Max Value:", np.max(matrix), "\n")

# ------------------------------------------------------------------------------
# STEP 10: Comparison & Broadcasting
# ------------------------------------------------------------------------------
print("--- STEP 10: COMPARISON & BROADCASTING ---")
comp1 = np.array([1, 5, 3])
comp2 = np.array([4, 5, 6])
print("Element-wise comparison (==):", comp1 == comp2)
print("Are entire arrays equal?:", np.array_equal(comp1, comp2))

# Broadcasting (2D array + 1D array)
broad_matrix = np.array([[1, 2, 3], [4, 5, 6]])
broad_vector = np.array([10, 20, 30])
print("Broadcasting Result (2D + 1D):\n", broad_matrix + broad_vector, "\n")

# ------------------------------------------------------------------------------
# STEP 11: Handling Null Values
# ------------------------------------------------------------------------------
print("--- STEP 11: HANDLING NULL VALUES ---")
clean_data = np.array([1.0, 2.0, np.nan, 4.0, np.inf])
print("Data with NaN and Infinity:", clean_data)
print("Boolean Mask for NaN values:", np.isnan(clean_data))
print("Replacing NaN/Inf with numbers:", np.nan_to_num(clean_data), "\n")

# ------------------------------------------------------------------------------
# STEP 12: Saving and Loading Arrays
# ------------------------------------------------------------------------------
print("--- STEP 12: SAVING & LOADING ARRAYS ---")
save_arr = np.array([10, 20, 30, 40])
# Saving the array locally in Colab workspace
np.save('my_colab_array.npy', save_arr)
print("Array successfully saved as 'my_colab_array.npy'")

# Loading the array back
loaded_arr = np.load('my_colab_array.npy')
print("Loaded Array from disk:", loaded_arr, "\n")

print("==============================================================================")
print("TUTORIAL COMPLETE! You are now ready to practice the homework assignment.")
print("==============================================================================")

--- STEP 2: VERSION CHECK ---
NumPy Version: 2.0.2

--- STEP 3: CREATING ARRAYS ---
1D Array:
 [1 2 3]
Type: <class 'numpy.ndarray'>
Dimensions (ndim): 1 

2D Array:
 [[1 2 3]
 [4 5 6]]
Dimensions (ndim): 2 

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions (ndim): 3 

--- STEP 4: ARRAY ATTRIBUTES ---
Shape of arr2: (2, 3)
Size of arr2 (Total elements): 6
Data Type of arr2: int64 

--- STEP 5: INITIALIZATION METHODS ---
Zeros Array (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array (1x3):
 [[1. 1. 1.]]
Full Array (3x2 with 9s):
 [[9 9]
 [9 9]
 [9 9]]
Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange (1 to 10 with step 2):
 [1 3 5 7 9]
linspace (4 elements between 1 and 10):
 [ 1.  4.  7. 10.]
Random Integers (3x3 from 1 to 100):
 [[83 58 53]
 [ 7 89 73]
 [87 73 34]] 

--- STEP 6: INDEXING & SLICING ---
Base 1D Array: [1 3 5 7 9]
Positive Index 0: 1
Negative Index -1: 9
Slicing (First 3 elements): [1 3 5]
Slicing with step 2: [1 5 9] 

Base 2D Array (arr2):
 [[1 2 3]

Section 1: Conceptual Quick-Fire
What is the fundamental difference between a standard Python list and a NumPy ndarray in terms of memory layout and data types?

If an array has a .shape of (4, 3), how many rows does it have? How many columns? What will its .size return?

Why does the slicing operation array[0:5] only return 5 elements (indices 0 through 4) instead of 6?

Explain what Broadcasting does when you add a 1D array of shape (3,) to a 2D array of shape (3, 3).

Section 2: Hands-On Coding Challenges
Task 1a: Initialize a 1D array containing all even numbers from 2 to 20 (inclusive).

Task 1b: Reshape this 1D array into a 2D array with 5 rows and 2 columns, and verify its .shape and .ndim.

Task 1c: Generate a 4x4 Identity Matrix using a built-in NumPy shortcut function.

Task 2a: Given a 2D matrix, write a single slice expression to extract the entire second row.

Task 2b: Given a 2D matrix, write a single slice expression to extract the entire third vertical column across all rows.

Task 2c: Given a 2D matrix, write a slice expression to extract a specific inner sub-matrix block of corner numbers.

Task 3a: Create a random integer matrix of shape (3, 3) with values ranging between 1 and 50.

Task 3b: Find the total sum, the mean value, and the maximum value of this random matrix.

Task 3c: Compute the Transpose of this random matrix and print it.

Section 3: Real-World Data Scenario
Mission 1 (Identify): Write a code snippet using a Boolean mask to count exactly how many missing (NaN) values are present in a raw sensor dataset.

Mission 2 (Clean): Replace all NaN and inf values with a baseline neutral number (like 0.0) so that mathematical models do not crash.

Mission 3 (Calibrate): Use NumPy broadcasting to subtract a systematic error of 1.5 units from all elements in your cleaned array in a single line of code.

Mission 4 (Format): Reshape a 10-element clean array into a 2D matrix of shape (5, 2) to prepare it for a machine learning model.

Mission 5 (Secure): Save the finalized data matrix locally as a binary file named calibrated_sensors.npy and reload it to verify it saved successfully.

In [2]:
import numpy as np

# ==== SECTION 2 SOLUTIONS ====
print("==== TASK 1 ====")
arr_1d = np.arange(2, 21, 2)
arr_2d = arr_1d.reshape((5, 2))
print("Reshaped 2D Array:\n", arr_2d)
print("Shape:", arr_2d.shape, "| Dimensions:", arr_2d.ndim)
print("Identity Matrix:\n", np.eye(4))

print("\n==== TASK 2 ====")
matrix_challenge = np.array([[10, 20, 30, 40],
                             [50, 60, 70, 80],
                             [90, 100, 110, 120]])
print("Second Row:", matrix_challenge[1, :])
print("Third Column:", matrix_challenge[:, 2])
print("Sub-matrix block:\n", matrix_challenge[1:3, 1:3])

print("\n==== TASK 3 ====")
rand_matrix = np.random.randint(1, 51, (3, 3))
print("Sum:", np.sum(rand_matrix))
print("Mean:", np.mean(rand_matrix))
print("Max:", np.max(rand_matrix))
print("Transpose:\n", rand_matrix.T)

# ==== SECTION 3 SOLUTION ====
print("\n==== SECTION 3: REAL-WORLD DATA CLEANING ====")
sensor_readings = np.array([22.5, 24.1, np.nan, 23.8, np.inf, 25.2, np.nan, 26.4, 21.9, 23.0])

# 1. Identify Damage
nan_count = np.sum(np.isnan(sensor_readings))
print(f"Number of NaN values found: {nan_count}")

# 2. Clean Data
cleaned_data = np.nan_to_num(sensor_readings, nan=0.0, posinf=25.0) # substituting defaults
print("Cleaned Data:", cleaned_data)

# 3. Broadcasting Calibration
calibrated_data = cleaned_data - 1.5
print("Calibrated Data (-1.5 broadcasted):", calibrated_data)

# 4. Reshape
final_matrix = calibrated_data.reshape((5, 2))
print("Reshaped Final Matrix (5x2):\n", final_matrix)

# 5. Save and Load
np.save('calibrated_sensors.npy', final_matrix)
loaded_check = np.load('calibrated_sensors.npy')
print("Loaded Array Successfully Verification:\n", loaded_check)

==== TASK 1 ====
Reshaped 2D Array:
 [[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
Shape: (5, 2) | Dimensions: 2
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

==== TASK 2 ====
Second Row: [50 60 70 80]
Third Column: [ 30  70 110]
Sub-matrix block:
 [[ 60  70]
 [100 110]]

==== TASK 3 ====
Sum: 196
Mean: 21.77777777777778
Max: 45
Transpose:
 [[24 22 26]
 [19 17  8]
 [12 23 45]]

==== SECTION 3: REAL-WORLD DATA CLEANING ====
Number of NaN values found: 2
Cleaned Data: [22.5 24.1  0.  23.8 25.  25.2  0.  26.4 21.9 23. ]
Calibrated Data (-1.5 broadcasted): [21.  22.6 -1.5 22.3 23.5 23.7 -1.5 24.9 20.4 21.5]
Reshaped Final Matrix (5x2):
 [[21.  22.6]
 [-1.5 22.3]
 [23.5 23.7]
 [-1.5 24.9]
 [20.4 21.5]]
Loaded Array Successfully Verification:
 [[21.  22.6]
 [-1.5 22.3]
 [23.5 23.7]
 [-1.5 24.9]
 [20.4 21.5]]
