<a href="https://colab.research.google.com/github/urmilapol/urmilapolprojects/blob/master/nympy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import time
import sys
import matplotlib.pyplot as plt  # For student viz exercise

print("NumPy Introduction: Arrays vs Lists (codebasics Tutorial)")
print("=" * 50)
print(f"NumPy version: {np.__version__}\n")

# 1. Memory Demo (Video ~3:48)
N = 10000
py_list = range(N)
np_arr = np.arange(N)
py_size = sys.getsizeof(1) * len(py_list)
np_size = np_arr.size * np_arr.itemsize
print("Memory Usage:")
print(f"Python list ({N} elements): {py_size} bytes")
print(f"NumPy array ({N} elements): {np_size} bytes")
print(f"NumPy uses {py_size / np_size:.1f}x less memory\n")

# 2. Speed Demo (Video ~5:08, scaled to 1M)
size = 1000000
l1, l2 = range(size), range(size)
a1, a2 = np.arange(size), np.arange(size)

start = time.time()
result_list = [x + y for x, y in zip(l1, l2)]
list_time = (time.time() - start) * 1000

start = time.time()
result_array = a1 + a2
array_time = (time.time() - start) * 1000

print("Speed Comparison (add 1M elements):")
print(f"Python list: {list_time:.2f} ms")
print(f"NumPy array: {array_time:.2f} ms")
print(f"NumPy is {list_time / array_time:.1f}x faster\n")

# 3. Operations Demo (Video ~11:00)
a1_small = np.array([1,2,3])
a2_small = np.array([4,5,6])
print("Array Operations:")
print(f"{a1_small} + {a2_small} = {a1_small + a2_small}")
print(f"{a1_small} - {a2_small} = {a1_small - a2_small}")
print(f"{a1_small} * {a2_small} = {a1_small * a2_small}")
print(f"{a1_small} / {a2_small} = {a1_small / a2_small}\n")

print("EXERCISES (Assign to students):")
print("1. Time np.sin(np.arange(1e6)) vs list comprehension.")
print("2. Create 2D array: np.array([[1,2],[3,4]]). Plot with plt.imshow().")
print("3. For ETL: Generate sales data np.random.randint(100,1000,10000), sum by chunks.")
print("Solutions: Extend in next cell!")


NumPy Introduction: Arrays vs Lists (codebasics Tutorial)
NumPy version: 2.0.2

Memory Usage:
Python list (10000 elements): 280000 bytes
NumPy array (10000 elements): 80000 bytes
NumPy uses 3.5x less memory

Speed Comparison (add 1M elements):
Python list: 93.89 ms
NumPy array: 3.94 ms
NumPy is 23.8x faster

Array Operations:
[1 2 3] + [4 5 6] = [5 7 9]
[1 2 3] - [4 5 6] = [-3 -3 -3]
[1 2 3] * [4 5 6] = [ 4 10 18]
[1 2 3] / [4 5 6] = [0.25 0.4  0.5 ]

EXERCISES (Assign to students):
1. Time np.sin(np.arange(1e6)) vs list comprehension.
2. Create 2D array: np.array([[1,2],[3,4]]). Plot with plt.imshow().
3. For ETL: Generate sales data np.random.randint(100,1000,10000), sum by chunks.
Solutions: Extend in next cell!
